# Generated by Django 2.1.2 on 2018-10-12 13:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
